### ISSUE TITLE
what is extension supposed to do? 

### ISSUE THREAD

**Issue by PeakyBlander3** [j0rd1s3rr4n0/Tinder-Osint-Tool#1]
After following all the steps and giving, what is extension supposed to do? When I hit activate with whatever information it does, it does nothing.

**Comment by j0rd1s3rr4n0** [comment]
# Understanding the Extension's Functionality

Thank you for your interest in our extension and for taking the time to open this issue. Let me explain how the extension works and what should happen after you activate it.

### What Does the Extension Do?

Our extension is designed to search for people in Tier using a swipe up gesture. Here are the detailed steps on how to use it:

1. **Access the Account:** First, log in to your account on the relevant platform.
2. **Navigate to the Home Screen:** Once logged in, go to the home screen of the platform.
3. **Use the Swipe Up Gesture:** On the home screen, use the swipe up gesture to activate the search function.
4. **Interact with the Extension:** When you swipe up, the extension should automatically activate and start searching for people in Tier based on the provided information.

### What to Expect When You Activate the Extension

When you press "Activate" with the required information:
- The extension should start interacting with the platform's window.
- You should see the extension performing searches for people in Tier.
- The search results should appear either in the extension's interface or in the same window of the platform.

### Possible Issues

If, after following these steps, the extension does not perform any action, you might be facing one of these problems:
- The information provided for the search is incorrect or insufficient.
- There is a technical issue with the extension that needs to be fixed.

Please verify that all steps have been followed correctly and that the information is accurate. If the problem persists, provide additional details about the error or any console messages so we can investigate further.

We appreciate your patience and cooperation.

**Comment by j0rd1s3rr4n0** [comment]
# Understanding the Extension's Functionality

Thank you for your interest in our extension and for taking the time to open this issue. Let me explain how the extension works and what should happen after you activate it.

### What Does the Extension Do?

Our extension is designed to search for people in Tier using a swipe up gesture. Here are the detailed steps on how to use it:

1. **Access the Account:** First, log in to your account on the relevant platform.
2. **Navigate to the Home Screen:** Once logged in, go to the home screen of the platform.
3. **Use the Swipe Up Gesture:** On the home screen, use the swipe up gesture to activate the search function.
4. **Interact with the Extension:** When you swipe up, the extension should automatically activate and start searching for people in Tier based on the provided information.

### What to Expect When You Activate the Extension

When you press "Activate" with the required information:
- The extension should start interacting with the platform's window.
- You should see the extension performing searches for people in Tier.
- The search results should appear either in the extension's interface or in the same window of the platform.

Any console error?

We appreciate your patience and cooperation.

**Comment by j0rd1s3rr4n0** [comment]
# Understanding the Extension's Functionality

Thank you for your interest in our extension and for taking the time to open this issue. Let me explain how the extension works and what should happen after you activate it.

### What Does the Extension Do?

Our extension is designed to search for people in Tier using a swipe up gesture. Here are the detailed steps on how to use it:

1. **Access the Account:** First, log in to your account on the relevant platform.
2. **Navigate to the Home Screen:** Once logged in, go to the home screen of the platform.
3. **Use the Swipe Up Gesture:** On the home screen, use the swipe up gesture to activate the search function.
4. **Interact with the Extension:** When you swipe up, the extension should automatically activate and start searching for people in Tier based on the provided information.

### What to Expect When You Activate the Extension

When you press "Activate" with the required information:
- The extension should start interacting with the platform's window.
- You should see the extension performing searches for people in Tier.
- The search results should appear either in the extension's interface or in the same window of the platform.

Any console error?

We appreciate your patience and cooperation.
